# Some overall notes on how this works
#
# * We smoke using the system provided latest, and custom built "oddball perls"
# The reason for not having a blanket matrix is to conserve travis resources
# as a full DBIC depchain isn't cheap
#
# * Minimum perl officially supported by DBIC is 5.8.3. This *includes* the
# basic depchain. On failure either attempt to fix it or bring it to the
# attention of the maintainer. *DO NOT* disable 5.8 testing - it is here for
# a very good reason
#
# the entire run times out after 50 minutes, or after 5 minutes without
# console output

#
# Smoke all branches except for blocked* and wip/*
branches:
  except:
    - /^wip\//
    - /^blocked/

notifications:
  email:
    recipients:
      - CPAN-CI@leporine.io
    on_success: change
    on_failure: always

# IFF this list is changed - make sure to backfill the override-addons further down too
addons:
  apt:
    packages:
      - libapp-nopaste-perl
      - net-tools
      - expect

# This is probably a net-loss for setup etc - a bare 'C' will likely fare much better
language: perl

# Currently not trying osx: https://github.com/travis-ci/travis-ci/issues/2314
os: linux

# The defaults run under the older infra.
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
dist: precise
env: CLEANTEST=false MVDT=true

perl:
  - "5.8"
  - "5.10"
  - "5.24-shrplib"

matrix:
  include:

    # ASan-instrumented threaded latest 5.24 with, no tests on depchain ( run only DBICs tests )
    - perl: "livebrew_devcpan_5.24.4_thr_qm_asan"
      # FIXME - move to bionic
      dist: trusty
      env:
        - CLEANTEST=false
        - POISON_ENV=true
        - MVDT=true
        - BREWVER=5.24.4
        - CC=gcc-8
        - CXX=g++-8
        # FIXME - something in perl confuses ASan, do no trace leaks for now
        #         https://www.nntp.perl.org/group/perl.perl5.porters/2018/03/msg250024.html
        #         https://www.nntp.perl.org/group/perl.perl5.porters/2018/03/msg250022.html
        - ASAN_OPTIONS=detect_leaks=0
        - ASAN_FLAGS_COMMON="-fsanitize=address -fuse-ld=gold -fno-omit-frame-pointer -g -O2"
        - BREWOPTS="-Duseithreads -Dusequadmath -Dcc=$CC -Accflags='$ASAN_FLAGS_COMMON' -Aldflags='$ASAN_FLAGS_COMMON'"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libapp-nopaste-perl
            - net-tools
            - expect
            - libc6
            - libc6:i386
            - binutils
            - gcc-8
            - g++-8


###
### For the following two phases -e is *set*
###

before_install:
  # common functions for all run phases below
  #
  # this is an exporter - sourcing it is crucial
  # among other things it also sets -e
  #
  - source maint/travis-ci_scripts/common.bash

  # Sets global envvars, downloads/configures debs based on CLEANTEST
  # Sets extra DBICTEST_* envvars
  #
  # this is an exporter - sourcing it is crucial
  #
  - source maint/travis-ci_scripts/10_before_install.bash

install:
  # Build and switch to a custom perl if requested
  # Configure the perl env, preinstall some generic toolchain parts
  # Possibly poison the environment
  #
  # this is an exporter - sourcing it is crucial
  #
  - source maint/travis-ci_scripts/20_install.bash

###
### From this point on -e is *unset*, rely on travis' error handling
###
  - set +e

before_script:
  # Preinstall/install deps based on envvars/CLEANTEST
  #
  # need to invoke the after_failure script manually
  # because 'after_failure' runs only after 'script' fails
  #
  - maint/getstatus maint/travis-ci_scripts/30_before_script.bash

script:
  # Run actual tests
  #
  - maint/getstatus maint/travis-ci_scripts/40_script.bash


after_success:
  # Check if we can assemble a dist properly if not in CLEANTEST
  #
  ### Need to toggle -e again: work around https://github.com/travis-ci/travis-ci/issues/3533
  - set -e
  - maint/getstatus /bin/bash maint/travis-ci_scripts/50_after_success.bash || ( /bin/bash maint/travis-ci_scripts/50_after_failure.bash && /bin/false )
  - set +e

after_failure:
  # Final sysinfo printout on fail
  #
  - maint/getstatus maint/travis-ci_scripts/50_after_failure.bash

after_script:
  # No tasks yet
  #
  #- maint/getstatus maint/travis-ci_scripts/60_after_script.bash
